Ref: helpme -> die

diff --git a/bin/pmc-pm-create b/bin/pmc-pm-create
--- a/bin/pmc-pm-create
+++ b/bin/pmc-pm-create
@@ -14,15 +14,15 @@ do
 #	pmc-pm-create -v PM
 #DESCRIPTION
 		-h | --help) #display help and exit
-			helpme ;;
+			die ;;
 		--version)	#display version and exit
-			helpme "20220918" ;;
+			die "20220918" ;;
 		-v | --verbose)	#verbose output
 			VERBOSE="set -x"
 			$VERBOSE
 			shift ;;
 		--)
-			[ $# -eq 2 ] || helpme "ERR-1001: PM is missing"
+			[ $# -eq 2 ] || die "ERR-1001: PM is missing"
 			PM=$2
 			shift 2
 			break ;;
@@ -38,7 +38,7 @@ do
 #HELPME_END
 	esac
 done
-element_in_array $PM ${PM_LIST[@]} || helpme "ERR-1002: add $PM to PM_LIST in /etc/pmc.conf first, please"
+element_in_array $PM ${PM_LIST[@]} || die "ERR-1002: add $PM to PM_LIST in /etc/pmc.conf first, please"
 ssh -t $PM "
 $VERBOSE
 set -Eeuo pipefail
@@ -67,7 +67,7 @@ ip a s br0
 echo '##checking vg'
 vgdisplay $VG_NAME
 echo '## VM_BACKUP_DIR'
-[ -d \"$VM_BACKUP_DIR\" ] || helpme \"ERR-1003: $VM_BACKUP_DIR does not exist\"
+[ -d \"$VM_BACKUP_DIR\" ] || die \"ERR-1003: $VM_BACKUP_DIR does not exist\"
 echo '##PASS'
 "
 for N in "${PM_LIST[@]}"
diff --git a/bin/pmc-pm-ready-drbd b/bin/pmc-pm-ready-drbd
--- a/bin/pmc-pm-ready-drbd
+++ b/bin/pmc-pm-ready-drbd
@@ -14,15 +14,15 @@ do
 #	pmc-pm-ready-drbd -v PM
 #DESCRIPTION
 		-h | --help) #display help and exit
-			helpme ;;
+			die ;;
 		--version)	#display version and exit
-			helpme "20220918" ;;
+			die "20220918" ;;
 		-v | --verbose)	#verbose output
 			VERBOSE="set -x"
 			$VERBOSE
 			shift ;;
 		--)
-			[ $# -eq 2 ] || helpme "ERR-1001: PM is missing"
+			[ $# -eq 2 ] || die "ERR-1001: PM is missing"
 			PM=$2
 			shift 2
 			break ;;
@@ -38,7 +38,7 @@ do
 #HELPME_END
 	esac
 done
-element_in_array $PM ${PM_LIST[@]} || helpme "ERR-1002: $PM is not defined in PM_LIST in /etc/pmc.conf"
+element_in_array $PM ${PM_LIST[@]} || die "ERR-1002: $PM is not defined in PM_LIST in /etc/pmc.conf"
 ssh -n $PM "
 $VERBOSE
 set -Eeuo pipefail
diff --git a/bin/pmc-vm-backup b/bin/pmc-vm-backup
--- a/bin/pmc-vm-backup
+++ b/bin/pmc-vm-backup
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 . /etc/pmc.conf
-[ "$VM_BACKUP_DIR" != "" ] || helpme "ERR-8000: VM_BACKUP_DIR is not defined in /etc/pmc.conf"
+[ "$VM_BACKUP_DIR" != "" ] || die "ERR-8000: VM_BACKUP_DIR is not defined in /etc/pmc.conf"
 HOST=""
-BASE=N
+BaseOpt=N
 OPTS=$(getopt -o hvbp: --long help,version,base,physical-host:, -n "$(basename $0)" -- "$@")
 eval set -- "$OPTS"
 while [ $# -gt 0 ]
@@ -17,15 +17,15 @@ do
 #	pmc-vm-backup wsus
 #DESCRIPTION
 		-h | --help) #display help and exit
-			helpme ;;
+			die ;;
 		--version)	#display version and exit
-			helpme "20220918" ;;
+			die "20250628" ;;
 		-v | --verbose)	#verbose output
 			VERBOSE="set -x"
 			$VERBOSE
 			shift ;;
 		-b | --base) #create base image
-			BASE=Y
+			BaseOpt=Y
 			shift ;;
 		-p | --physical-host) #specify the physical host instead of finding out the secondary DRBD host.
 			HOST=$2
@@ -39,7 +39,7 @@ do
 #	There is NO WARRANTY, to the extent permitted by law.
 #HELPME_END
 		--)
-			[ $# -eq 2 ] || helpme "ERR-8001: VM is missing"
+			[ $# -eq 2 ] || die "ERR-8001: VM is missing"
 			VM=$2
 			shift 2
 			break ;;
@@ -47,7 +47,7 @@ do
 			break ;;
 	esac
 done
-[ $# -eq 0 ] || helpme "ERR-8002: use -h/--help"
+[ $# -eq 0 ] || die "ERR-8002: use -h/--help"
 if [ -z "$HOST" ]
 then
 	for PM in ${PM_LIST[@]}
@@ -58,21 +58,21 @@ then
 			PRIMARY=$PM
 		elif [ "$STATE" = "shut off" ]
 		then
-			[ -z "$HOST" ] || helpme "ERR-8003: VM $VM is not running, add '-p' to specify the physical host that runs the backup"
+			[ -z "$HOST" ] || die "ERR-8003: VM $VM is not running, add '-p' to specify the physical host that runs the backup"
 			HOST=$PM
 		fi
 	done
 else
-	ssh -n $HOST "virsh dominfo $VM &>/dev/null" || helpme "ERR-8007: VM $VM is the physical host you specified with '-p'"
+	ssh -n $HOST "virsh dominfo $VM &>/dev/null" || die "ERR-8007: VM $VM is the physical host you specified with '-p'"
 fi
-[ ! -z "$HOST" ] || helpme "ERR-8004: VM $VM is not running, add '-p' to specify the physical host that runs the backup"
+[ ! -z "$HOST" ] || die "ERR-8004: VM $VM is not running, add '-p' to specify the physical host that runs the backup"
 TS=$(date +%+4Y-%m-%d-%H-%M-%S)
 ssh -T $HOST << EOF
 	$VERBOSE
 	[[ $- == *x* ]] && set -x
 	set -Eeuo pipefail
 	$HELPME_FUNC
-	[ "\$(drbdadm status $VM | grep disk:UpToDate | wc -l)" = "2" ] || helpme "ERR-8005: This VM's drbd is not in a normal status"
+	[ "\$(drbdadm status $VM | grep disk:UpToDate | wc -l)" = "2" ] || die "ERR-8005: This VM's drbd is not in a normal status"
 	VID=\$(grep "^	device /dev/drbd" /etc/drbd.d/$VM.res | sed -e "s/;//; s/^.*minor //")
 	cd "$VM_BACKUP_DIR"
 	mkdir -p $VM
@@ -83,14 +83,14 @@ ssh -T $HOST << EOF
 		ROLE_PRIMARY=Y
 	fi
 	[ ! -z "\$ROLE_PRIMARY" ] || drbdadm primary $VM
-	if [ "$BASE" = "Y" ]
+	if [ "$BaseOpt" = "Y" ]
 	then
 		flock .lock dd if=/dev/drbd\$VID of=$TS.base.tmp bs=16M status=progress
 		mv $TS.base.tmp $TS.base
 	else
-		BASE="\$( ls -t *.base 2> /dev/null | head -n 1 )"
-		[ "\$BASE" != "" ] || helpme "ERR-8006: no base image exists under $HOST:$VM_BACKUP_DIR/$VM/"
-		flock -s .lock xdelta3 -e -S djw -s "\$BASE" /dev/drbd\$VID $TS.xdelta3.tmp
+		BaseImg="\$( ls -t *.base 2> /dev/null | head -n 1 )" || :
+		[ "\$BaseImg" != "" ] || die "ERR-8006: no base image exists under $HOST:$VM_BACKUP_DIR/$VM/, use '-b'"
+		flock -s .lock xdelta3 -e -S djw -s "\$BaseImg" /dev/drbd\$VID $TS.xdelta3.tmp
 		mv $TS.xdelta3.tmp $TS.xdelta3
 	fi
 	[ ! -z "\$ROLE_PRIMARY" ] || drbdadm secondary $VM
diff --git a/bin/pmc-vm-create b/bin/pmc-vm-create
--- a/bin/pmc-vm-create
+++ b/bin/pmc-vm-create
@@ -81,19 +81,19 @@ else
 	fi
 fi
 EOF
-		[ $? -eq 0 ] || helpme "ERR-2502: set_drbd failed on host $PM"
+		[ $? -eq 0 ] || die "ERR-2502: set_drbd failed on host $PM"
 	done
 	for ((i=0; i<100; i++))
 	do
 		ssh ${PMS[0]} drbdadm status $VM |grep -q "disk:UpToDate" && return 0
 		sleep 1
 	done
-	helpme "ERR-2503: drbd failure on host ${PMS[0]}"
+	die "ERR-2503: drbd failure on host ${PMS[0]}"
 }
 function check_resource() {
 	for PM in ${PMS[@]}
 	do
-		element_in_array $PM "${PM_LIST[@]}" || helpme "ERR-2101: $PM is not defined in etc/pmc/pmc.conf"
+		element_in_array $PM "${PM_LIST[@]}" || die "ERR-2101: $PM is not defined in etc/pmc/pmc.conf"
 		if ! ssh -T $PM << EOF
 $VERBOSE
 let rtn=0
@@ -145,9 +145,9 @@ do
 #	pmc-vm-create -p pm-1 -p pm-2 -s 50 -m 4 -c 8 -V "--machine pc --nographics --pxe --osinfo archlinux" test-vm
 #DESCRIPTION
 		-h | --help) #display help and exit
-			helpme ;;
+			die ;;
 		--version)	#display version and exit
-			helpme "20241025" ;;
+			die "20241025" ;;
 		-v | --verbose)	#verbose output
 			VERBOSE="set -x"
 			$VERBOSE
@@ -184,7 +184,7 @@ do
 			CLONEPM=$2
 			shift 2 ;;
 		--)
-			[ $# -eq 2 ] || helpme "ERR-2001: VM is missing"
+			[ $# -eq 2 ] || die "ERR-2001: VM is missing"
 			VM=$2
 			shift 2
 			break ;;
@@ -202,34 +202,34 @@ do
 done
 if [ $# -ne 0 ]
 then
-	helpme "ERR-2002: use -h/--help"
+	die "ERR-2002: use -h/--help"
 elif [ ${#PMS[@]} -eq 0 ]
 then
-	helpme "ERR-2003: -p/--physical-host is mandatory"
+	die "ERR-2003: -p/--physical-host is mandatory"
 elif [ "$STORAGE" = "" ]
 then
-	helpme "ERR-2019: -s/--storage is wrong"
+	die "ERR-2019: -s/--storage is wrong"
 elif [ "$STORAGE" != "reuse" -a "$STORAGE" = "0" ]
 then
-	helpme "ERR-2004: -s/--storage is wrong"
+	die "ERR-2004: -s/--storage is wrong"
 elif [ "$MEMORY" = "" ]
 then
-	helpme "ERR-2020: -m/--memory is wrong"
+	die "ERR-2020: -m/--memory is wrong"
 elif [ $MEMORY -le 0 ]
 then
-	helpme "ERR-2005: -m/--memory is wrong"
+	die "ERR-2005: -m/--memory is wrong"
 elif [ "$VCPUS" = "" ]
 then
-	helpme "ERR-2021: -c/--vcpus is wrong"
+	die "ERR-2021: -c/--vcpus is wrong"
 elif [ "$VCPUS" -le 0 ]
 then
-	helpme "ERR-2006: -c/--vcpus is wrong"
+	die "ERR-2006: -c/--vcpus is wrong"
 elif ! echo $VM | grep -Eq '^[a-z0-9-]+$'
 then
-	helpme "ERR-2008: $VM should be [a-z0-9-]"
+	die "ERR-2008: $VM should be [a-z0-9-]"
 elif [ ${#PMS[@]} -ne 1 -a ${#PMS[@]} -ne 2 ]
 then
-	helpme "ERR-2009: up to two -p are supported for now"
+	die "ERR-2009: up to two -p are supported for now"
 fi
 if [[ -v CLONEVM ]]
 then
@@ -242,7 +242,7 @@ then
 			break
 		done
 	else
-		ssh -n $CLONEPM "drbdadm status $CLONEVM" | grep -q "^$CLONEVM role:Primary" || helpme "ERR-2010: drbd resource $CLONEVM is not in primary status on $CLONEPM"
+		ssh -n $CLONEPM "drbdadm status $CLONEVM" | grep -q "^$CLONEVM role:Primary" || die "ERR-2010: drbd resource $CLONEVM is not in primary status on $CLONEPM"
 	fi
 	echo $CLONEPM
 fi
@@ -253,16 +253,16 @@ then
 fi
 for PM in ${PM_LIST[@]}
 do
-	ssh $PM virsh dominfo $VM 2> /dev/null | grep -q "State:          running" && helpme "ERR-2011: $VM is running on $PM, run \"pmc-vm-rm $VM\" or stop the VM before running 'pmc-vm-create -R'"
+	ssh $PM virsh dominfo $VM 2> /dev/null | grep -q "State:          running" && die "ERR-2011: $VM is running on $PM, run \"pmc-vm-rm $VM\" or stop the VM before running 'pmc-vm-create -R'"
 done
 
 if [[ ! -v IP ]]
 then
-	IP=$(host $VM) || helpme "ERR-2018: $VM not in DNS"
-	[ "$IP" != "" ] || helpme "ERR-2012: $VM not in DNS"
+	IP=$(host $VM) || die "ERR-2018: $VM not in DNS"
+	[ "$IP" != "" ] || die "ERR-2012: $VM not in DNS"
 elif [[ ! $IP =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
 then
-		helpme "ERR-2013: invalid IP address $IP"
+		die "ERR-2013: invalid IP address $IP"
 fi
 IP=$(echo $IP | cut -d " " -f 4)
 MAC=$( (echo "obase=16;"; echo $IP | cut -d . -f 3- |sed -e "s/\./\n/g" ) | bc | sed -e "s/^.$/0&/" | sed -e "N; s/\n/:/g" | sed -e "s/^/52:54:00:$MAC4:/" )
@@ -276,18 +276,18 @@ then
 	then
 		set_drbd
 	else
-		ssh -n ${PMS[0]} drbdadm status $VM || helpme "ERR-2007: Drbd resource $VM does not exist on ${PMS[0]}"
+		ssh -n ${PMS[0]} drbdadm status $VM || die "ERR-2007: Drbd resource $VM does not exist on ${PMS[0]}"
 		exit 9
 	fi
 	if [ ${#PMS[@]} -eq 2 ]
 	then
 		CPU=$( ssh ${PMS[0]} "virsh cpu-baseline --migratable <(virsh capabilities; ssh ${PMS[1]} virsh capabilities)" | grep "<model \|feature policy='require'" | sed -e "s/.*>\(.*\)<\/model>/\1/; s/.*name='\(.*\)'\/>/\1/" | sed -e :a -e "N;s/\n/,require=/;ta" )
-		[ "$CPU" != "" ] || helpme 'ERR-2014: Incompatible CPU between the two hosts'
+		[ "$CPU" != "" ] || die 'ERR-2014: Incompatible CPU between the two hosts'
 	else
 		CPU=host
 	fi
 else
-	helpme 'ERR-2017: three or more PM are not supported yet'
+	die 'ERR-2017: three or more PM are not supported yet'
 	exit 1
 fi
 
@@ -295,8 +295,8 @@ ssh -t ${PMS[0]} "virsh undefine $VM" &> /dev/null || echo -n
 if [[ -v CLONEVM ]]
 then
 	CLONEVID=$(ssh -n $CLONEPM "grep '^	device /dev/drbd' /etc/drbd.d/$CLONEVM.res | sed -e 's/;//; s/^.*minor //'")
-	[ -n "$CLONEVID" ] || helpme "ERR-2020: cannot find VID for $CLONEVM"
-	[ $(ssh -n $CLONEPM "grep -w drbd$CLONEVID /proc/partitions" | tr -s " " | cut -d " " -f 4) -le $(ssh -n ${PMS[0]} "grep -w drbd$VID /proc/partitions" | tr -s " " | cut -d " " -f 4) ] || helpme "ERR-2022: -s is too small for the VM you want to clone"
+	[ -n "$CLONEVID" ] || die "ERR-2020: cannot find VID for $CLONEVM"
+	[ $(ssh -n $CLONEPM "grep -w drbd$CLONEVID /proc/partitions" | tr -s " " | cut -d " " -f 4) -le $(ssh -n ${PMS[0]} "grep -w drbd$VID /proc/partitions" | tr -s " " | cut -d " " -f 4) ] || die "ERR-2022: -s is too small for the VM you want to clone"
 	ssh -n ${PMS[0]} drbdadm primary $VM
 	if [ "${PMS[0]}" = "$CLONEPM" ]
 	then
diff --git a/bin/pmc-vm-recreate-peer b/bin/pmc-vm-recreate-peer
--- a/bin/pmc-vm-recreate-peer
+++ b/bin/pmc-vm-recreate-peer
@@ -15,23 +15,23 @@ do
 #	pmc-vm-recreate-peer -t pm-1 win10
 #DESCRIPTION
 		-h | --help) #display help and exit
-			helpme ;;
+			die ;;
 		--version)	#display version and exit
-			helpme "20220918" ;;
+			die "20220918" ;;
 		-v | --verbose)	#verbose output
 			VERBOSE="set -x"
 			$VERBOSE
 			shift ;;
 		-F | --from-physical-host) #optional
 			PRIMARY=$2
-			host $PRIMARY &> /dev/null || helpme "ERR-7001: $PRIMARY is not a valid physical host"
+			host $PRIMARY &> /dev/null || die "ERR-7001: $PRIMARY is not a valid physical host"
 			shift 2 ;;
 		-t | --to-physical-host) #mandatory
 			NEW=$2
-			host $NEW &> /dev/null || helpme "ERR-7002: $NEW is not a valid physical host"
+			host $NEW &> /dev/null || die "ERR-7002: $NEW is not a valid physical host"
 			shift 2 ;;
 		--)
-			[ $# -eq 2 ] || helpme "ERR-7001: VM is missing"
+			[ $# -eq 2 ] || die "ERR-7001: VM is missing"
 			VM=$2
 			shift 2
 			break ;;
@@ -49,7 +49,7 @@ do
 done
 if [ $# -ne 0 ]
 then
-	helpme "ERR-7004: use -h/--help"
+	die "ERR-7004: use -h/--help"
 fi
 declare -a OLD
 for PM in ${PM_LIST[@]}
@@ -62,14 +62,14 @@ do
 			PRIMARY=$PM
 		elif [ "$PRIMARY" != "$PM" ]
 		then
-			helpme "ERR-7005: the VM is running on $PM, but you specified \"-F $PRIMARY\""
+			die "ERR-7005: the VM is running on $PM, but you specified \"-F $PRIMARY\""
 		fi
 	elif [ "$STATE" = "shut off" ]
 	then
 		OLD+=($PM)
 	fi
 done
-[ "$PRIMARY" != "" ] || helpme "ERR-7006: invalid $VM. If it is not running, please specify -F"
+[ "$PRIMARY" != "" ] || die "ERR-7006: invalid $VM. If it is not running, please specify -F"
 for OPM in ${OLD[@]}
 do
 	[ "$OPM" == "$PRIMARY" ] && continue
@@ -87,9 +87,9 @@ do
 	delete_vm_from_pm $VM $OPM
 done
 IPP=$(host $PRIMARY | cut -d " " -f 4)
-[ "$IPP" != "" ] || helpme "ERR-7007: cannot resolve $PRIMARY to ip address"
+[ "$IPP" != "" ] || die "ERR-7007: cannot resolve $PRIMARY to ip address"
 IPS=$(host $NEW | cut -d " " -f 4)
-[ "$IPS" != "" ] || helpme "ERR-7008: cannot resolve $NEW to ip address"
+[ "$IPS" != "" ] || die "ERR-7008: cannot resolve $NEW to ip address"
 ssh -T $PRIMARY << EOF
 	$VERBOSE
 	set -Eeuo pipefail
diff --git a/bin/pmc-vm-rm b/bin/pmc-vm-rm
--- a/bin/pmc-vm-rm
+++ b/bin/pmc-vm-rm
@@ -14,15 +14,15 @@ do
 #	pmc-vm-rm wsus
 #DESCRIPTION
 		-h | --help) #display help and exit
-			helpme ;;
+			die ;;
 		--version)	#display version and exit
-			helpme "20220918" ;;
+			die "20220918" ;;
 		-v | --verbose)	#verbose output
 			VERBOSE="set -x"
 			$VERBOSE
 			shift ;;
 		--)
-			[ $# -eq 2 ] || helpme "ERR-3001: VM is missing"
+			[ $# -eq 2 ] || die "ERR-3001: VM is missing"
 			VM=$2
 			shift 2
 			break ;;
@@ -40,7 +40,7 @@ do
 done
 if [ $# -ne 0 ]
 then
-	helpme "ERR-3002: use -h/--help"
+	die "ERR-3002: use -h/--help"
 fi
 read -p "Deleting \"$VM\", type \"$VM\" to confirm: " ANS
 if [ "$ANS" != "$VM" ]
